# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leveltests', '0003_auto_20170325_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.DecimalField(choices=[(1, '10-11'), (2, '11-12'), (3, '16-17'), (4, '17-18'), (5, '18-19'), (5, '19-20')], decimal_places=0, default=1, max_digits=1, verbose_name='Hour'),
            preserve_default=False,
        ),
    ]
