# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre (*)')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s) (*)')),
                ('birth_date', models.DateField(help_text='Formato: AAAA-MM-DD(ano-mes-dia)', verbose_name='Birth Date')),
                ('telephone', models.CharField(max_length=12, verbose_name='Tel. Fijo (*)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email (*)')),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('accept_conditions', models.BooleanField(default=True, help_text='You must accept the conditions to register', verbose_name='Accept the conditions')),
                ('venue', models.DecimalField(choices=[(1, 'Genaro Ora'), (2, 'Kabiezes')], decimal_places=0, max_digits=1, verbose_name='Venue')),
            ],
        ),
    ]
