# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasnivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.DecimalField(choices=[(1, 'Genaro Ora'), (2, 'Kabiezes')], decimal_places=0, max_digits=1, verbose_name='Venue')),
                ('hour', models.DecimalField(choices=[(1, '10-11'), (2, '11-12'), (3, '16-17'), (4, '17-18'), (5, '18-19'), (5, '19-20')], decimal_places=0, max_digits=1, verbose_name='Hour')),
                ('weekday', models.DecimalField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], decimal_places=0, max_digits=1, verbose_name='Week Day')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='birth_date',
            field=models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Birth Date'),
        ),
    ]
