# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0002_auto_20160729_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intensivo',
            options={'ordering': ['-inicio']},
        ),
        migrations.AddField(
            model_name='registration',
            name='venue',
            field=models.CharField(default=b'EIDE', max_length=50, verbose_name='Centro donde desea realizar el curso'),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='fin',
            field=models.DateField(help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='inicio',
            field=models.DateField(help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', verbose_name='Fecha NAc.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='intensivos',
            field=models.ManyToManyField(help_text=b'Recuerde que debe elegir todos los horarios a los que le sea posible asistir. Para seleccionar varios horarios use la tecla CTRL y haga click con el rat\xc3\xb3n en todas las opciones', to='intensivos.Intensivo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
    ]
